scss_files: client/scss/*.scss

linters:
  HexLength:
    style: long
  Indentation:
    width: 4
  LeadingZero:
    style: include_zero
  PropertySortOrder:
    order: concentric
  SelectorFormat:
    convention: hyphenated_lowercase
  SingleLinePerProperty:
    allow_single_line_rule_sets: false
  SpaceBeforeBrace:
    style: new_line
  SpaceBetweenParens:
    spaces: 1
